[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "fesslix"
version = "0.1.0"
description = "stochastic analysis"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{ name = "Wolfgang Betz", email = "w.betz@fesslix.org" }]
maintainers = [{ name = "Wolfgang Betz", email = "w.betz@fesslix.org" }]
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]

[project.urls]
Homepage = "http://fesslix.org"
#Documentation = "https://readthedocs.org"
Repository = "https://github.com/fesslix/fesslix.git"
Issues = "https://github.com/fesslix/fesslix/issues"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
minimum-version = "build-system.requires"

[tool.cibuildwheel]
#archs = ["AMD64"]
#archs = ["x86_64"]  #, "aarch64"
build = "cp312-* cp313-*"   # cp39-* cp310-* cp311-* cp312-*

[tool.cibuildwheel.linux]
before-all = "yum install -y gsl-devel boost-devel"
test-command = "echo 'installed 20250220844'"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add --no-cache gsl gsl-dev boost-dev"
