[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "fesslix"
version = "0.1.1"
description = "stochastic analysis"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{ name = "Wolfgang Betz", email = "w.betz@fesslix.org" }]
maintainers = [{ name = "Wolfgang Betz", email = "w.betz@fesslix.org" }]
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]

[project.urls]
Homepage = "http://fesslix.org"
#Documentation = "https://readthedocs.org"
Repository = "https://github.com/fesslix/fesslix.git"
Issues = "https://github.com/fesslix/fesslix/issues"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
minimum-version = "build-system.requires"

[tool.cibuildwheel]
build = "cp312-* cp313-*"   # cp39-* cp310-* cp311-* cp312-*

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]
before-all = "yum install -y gsl-devel boost-devel"
test-command = "echo 'installed gsl-devel boost-devel'"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add --no-cache gsl gsl-dev boost-dev"

[tool.cibuildwheel.windows]
archs = ["auto", "ARM64"]
before-build = "powershell -ExecutionPolicy Bypass -File windows_install_dependencies.ps1"

#[[tool.cibuildwheel.overrides]]
## overrides for X86
#select ="*-win_amd64*"
## use nuget to install gsl on Windows, and manually supply paths
#before-build = "nuget install gsl-msvc14-x64 -Version 2.3.0.2779"
#inherit.environment="append"
#environment = { CPATH="gsl-msvc14-x64.2.3.0.2779\\\\build\\\\native", LIBRARY_PATH="gsl-msvc14-x64.2.3.0.2779\\\\build\\\\native\\\\static" }


#[[tool.cibuildwheel.overrides]]
## overrides for ARM64
#select ="*-win_arm64*"
#before-build = 'nuget install gsl-msvc14-arm64 -Source "%CD%\\vendor-binaries"'
## use local nuget package to install gsl on Windows ARM64, and manually supply paths
#inherit.environment = "append"
#environment = { CPATH="gsl-msvc14-arm64.2.3.0.2779\\\\build\\\\native\\\\include", LIBRARY_PATH="gsl-msvc14-arm64.2.3.0.2779\\\\build\\\\native\\\\lib" }

