[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "fesslix"
version = "0.1.0"
description = "stochastic analysis"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{ name = "Wolfgang Betz", email = "w.betz@fesslix.org" }]
maintainers = [{ name = "Wolfgang Betz", email = "w.betz@fesslix.org" }]
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]

[project.urls]
Homepage = "http://fesslix.org"
#Documentation = "https://readthedocs.org"
Repository = "https://github.com/fesslix/fesslix.git"
Issues = "https://github.com/fesslix/fesslix/issues"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
minimum-version = "build-system.requires"

[tool.cibuildwheel]
build = "cp312-* cp313-*"   # cp39-* cp310-* cp311-* cp312-*

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]
before-all = "yum install -y gsl-devel boost-devel"
test-command = "echo 'installed gsl-devel boost-devel'"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add --no-cache gsl gsl-dev boost-dev"

[tool.cibuildwheel.windows]
archs = ["auto", "ARM64"]
before-build = '''
  powershell -Command "
    try {
      Write-Output 'Cloning vcpkg repository...';
      git clone https://github.com/microsoft/vcpkg.git;
      Write-Output 'Bootstrapping vcpkg...';
      .\\vcpkg\\bootstrap-vcpkg.bat;
      Write-Output 'Installing GSL and Boost...';
      .\\vcpkg\\vcpkg install gsl boost;
      Write-Output 'Setting environment variables...';
      $env:VCPKG_ROOT = \"$PWD\\vcpkg\";
      $env:CMAKE_TOOLCHAIN_FILE = \"$env:VCPKG_ROOT\\scripts\\buildsystems\\vcpkg.cmake\";
      Write-Output 'Setup completed successfully.';
    } catch {
      Write-Error 'An error occurred during setup:';
      Write-Error $_.Exception.Message;
      exit 1;
    }
  '''
