name: Python package CI

# Trigger the workflow on push and pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    # Run this job on multiple operating systems (Linux, Windows, macOS)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]  # List of OS to build on   , windows-latest, macos-latest ubuntu-latest, 

    permissions:
      id-token: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Get the code from the repository
      
    - name: Set up QEMU ## for aarch64
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.13' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-build-core pybind11 cmake build 
        pip install twine cibuildwheel
        
    - name: Run vcpkg
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '**/vcpkg.json'
      run: vcpkg install --triplet x64-windows
      shell: pwsh
        
    - name: Build the extension
      run: |
        python -m cibuildwheel --output-dir dist

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
        
