name: Test loading of the Python module

on:
  workflow_run:
    workflows: ["Build and publish Fesslix as Python module"]
    types:
      - completed

jobs:
  test-module-load:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-14, macos-13 ]  # List of OS to build on »  ubuntu-latest, windows-latest, macos-14, macos-13
        python: ['3.13']

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip and prepare environment
        run: |
          python -m pip install --upgrade pip

      - name: Wait for PyPI to synchronize (5 minutes)
        run: sleep 300

      - name: Install fesslix from PyPI
        run: |
          python -m pip install --no-cache-dir --upgrade fesslix

      - name: Run test script
        run: |
          run: python test_module_load.py
        working-directory: tests
